"""The one-pager's house style: every colour, size, and measurement in one file.

Spec §9 asks for the palette and the logo path to sit in CSS custom properties at the top
of one stylesheet, so re-skinning is a one-file change. The ReportLab engine has no
stylesheet, so this module is that promise kept in the form the engine can use: nothing
below this file hard-codes a colour, a font, or a band height.

The palette is three values doing three jobs — near-black for text, one TEN Capital accent
for structure, one neutral grey for everything subordinate — plus two tints for the bands
that need to recede. A fourth hue would have to earn its place by meaning something.
"""

from __future__ import annotations

from pathlib import Path

from reportlab.lib.colors import Color, HexColor

# --- Palette --------------------------------------------------------------------------

#: Body text. Not pure black: on a laser printer #000 blooms slightly against 8pt type.
INK = HexColor("#14181F")
#: The single accent. TEN Capital navy, used for rules, headings, and the ask strip.
ACCENT = HexColor("#1F3864")
#: Everything subordinate: labels, provenance, the em dash that means "the deck is silent".
MUTED = HexColor("#6B7280")
#: The ask strip. Accent at low saturation so the numbers stay the loudest thing on it.
TINT_ASK = HexColor("#EEF2F8")
#: The analyst block, which must never be mistaken for something the founders wrote.
TINT_ANALYST = HexColor("#F6F5F2")
RULE = HexColor("#D8DCE3")
WHITE = HexColor("#FFFFFF")

# --- Typography -----------------------------------------------------------------------
# One serif for headings, one sans for body (spec §9). Both are ReportLab base-14 fonts, so
# no font file has to ship or resolve at render time — a missing font is a class of failure
# this document does not need.

SERIF = "Times-Roman"
SERIF_BOLD = "Times-Bold"
SERIF_ITALIC = "Times-Italic"
SANS = "Helvetica"
SANS_BOLD = "Helvetica-Bold"
SANS_ITALIC = "Helvetica-Oblique"

SIZE_COMPANY = 22.0
SIZE_TAGLINE = 10.0
SIZE_ASK_VALUE = 11.0
SIZE_HEADING = 9.5
SIZE_BODY = 8.0
SIZE_CHIP = 7.5
SIZE_LABEL = 6.5
SIZE_METRIC_VALUE = 11.0
SIZE_FOOTER = 6.5
#: The low-confidence dagger, raised above the baseline it follows.
SIZE_DAGGER = 5.5
DAGGER_RISE = 3.0

LEADING = 1.30

# --- Page -----------------------------------------------------------------------------

MARGIN = 36.0  # 0.5in, spec §9
COLUMN_GAP = 14.0
#: Spec §9: left column 58%, right 42%.
LEFT_COLUMN_RATIO = 0.58
RULE_WIDTH = 0.6

#: Band heights from spec §9, in points. These are targets rather than a fixed grid: the
#: body takes whatever the header, ask strip, analyst block, and footer leave behind, which
#: is what keeps the page to one page when a deck is unusually rich.
HEIGHT_HEADER = 62.0
HEIGHT_ASK = 38.0
GAP_BAND = 10.0
HEIGHT_FOOTER = 14.0

#: Rendered height of the logo. The asset is 631x232, so the width follows from the ratio.
LOGO_HEIGHT = 17.0
LOGO_RATIO = 631 / 232

#: Resolved from the repo root; the renderer degrades gracefully when it is absent.
LOGO_PATH = Path(__file__).resolve().parents[3] / "assets" / "TEN_Capital_logo_footer.png"

# --- Fixed strings ---------------------------------------------------------------------

#: Spec §3: a field the deck does not support renders as an em dash, never as a guess.
EMPTY = "—"
DAGGER = "†"
ANALYST_LABEL = "TEN Capital analysis — AI-generated"
FOOTER_TEMPLATE = "Generated by TEN Capital · {filename} · {date} · Internal use only"
DAGGER_FOOTNOTE = "{dagger} below {threshold:.0%} confidence — verify before relying on it"


def tint(color: Color, amount: float) -> Color:
    """Mix `color` toward white by `amount` (0 = unchanged, 1 = white)."""
    return Color(
        color.red + (1.0 - color.red) * amount,
        color.green + (1.0 - color.green) * amount,
        color.blue + (1.0 - color.blue) * amount,
    )
